import { describe, test, expect, beforeAll } from "bun:test";
import { createTestClient, createTestWorkspace, getBaseUrl, testId } from "./helpers/api-client";

describe("custom emoji", () => {
  let client: Awaited<ReturnType<typeof createTestClient>>["client"];
  let headers: Record<string, string>;
  let slug: string;

  beforeAll(async () => {
    const ctx = await createTestClient();
    client = ctx.client;
    headers = ctx.headers;

    const workspace = await createTestWorkspace(client);
    slug = workspace.slug;
  });

  // Helper: create a 4x4 red PNG (generated by sharp, known to be valid)
  function createTestImage(): File {
    const pngBytes = new Uint8Array([
      137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,4,0,0,0,4,
      8,6,0,0,0,169,241,158,126,0,0,0,9,112,72,89,115,0,0,3,232,0,0,
      3,232,1,181,123,82,107,0,0,0,18,73,68,65,84,120,156,99,248,207,
      192,240,31,25,51,144,46,0,0,60,64,31,225,224,129,119,180,0,0,0,
      0,73,69,78,68,174,66,96,130,
    ]);
    return new File([pngBytes], "test.png", { type: "image/png" });
  }

  test("upload emoji → 201", async () => {
    const name = `emoji-${testId()}`;
    const formData = new FormData();
    formData.append("name", name);
    formData.append("file", createTestImage());

    const res = await fetch(`${getBaseUrl()}/api/workspaces/${slug}/emoji`, {
      method: "POST",
      headers,
      body: formData,
    });

    expect(res.status).toBe(201);
    const data = (await res.json()) as { emoji: { id: string; name: string; url: string } };
    expect(data.emoji.name).toBe(name);
    expect(data.emoji.url).toBeTruthy();
  });

  test("list emoji includes uploaded emoji", async () => {
    const name = `list-${testId()}`;
    const formData = new FormData();
    formData.append("name", name);
    formData.append("file", createTestImage());

    await fetch(`${getBaseUrl()}/api/workspaces/${slug}/emoji`, {
      method: "POST",
      headers,
      body: formData,
    });

    const res = await client.api.workspaces[":slug"].emoji.$get({
      param: { slug },
    });
    expect(res.status).toBe(200);
    const data = (await res.json()) as { emojis: Array<{ name: string }> };
    expect(data.emojis.some((e) => e.name === name)).toBe(true);
  });

  test("delete emoji → 200", async () => {
    const name = `del-${testId()}`;
    const formData = new FormData();
    formData.append("name", name);
    formData.append("file", createTestImage());

    const createRes = await fetch(`${getBaseUrl()}/api/workspaces/${slug}/emoji`, {
      method: "POST",
      headers,
      body: formData,
    });
    const created = (await createRes.json()) as { emoji: { id: string } };

    const res = await client.api.workspaces[":slug"].emoji[":emojiId"].$delete({
      param: { slug, emojiId: created.emoji.id },
    });
    expect(res.status).toBe(200);

    // Verify it's gone from the list
    const listRes = await client.api.workspaces[":slug"].emoji.$get({
      param: { slug },
    });
    const data = (await listRes.json()) as { emojis: Array<{ name: string }> };
    expect(data.emojis.some((e) => e.name === name)).toBe(false);
  });

  test("duplicate name → 409", async () => {
    const name = `dup-${testId()}`;
    const formData1 = new FormData();
    formData1.append("name", name);
    formData1.append("file", createTestImage());

    const res1 = await fetch(`${getBaseUrl()}/api/workspaces/${slug}/emoji`, {
      method: "POST",
      headers,
      body: formData1,
    });
    expect(res1.status).toBe(201);

    const formData2 = new FormData();
    formData2.append("name", name);
    formData2.append("file", createTestImage());

    const res2 = await fetch(`${getBaseUrl()}/api/workspaces/${slug}/emoji`, {
      method: "POST",
      headers,
      body: formData2,
    });
    expect(res2.status).toBe(409);
  });

  test("invalid name → 400", async () => {
    const formData = new FormData();
    formData.append("name", "X");  // too short, uppercase
    formData.append("file", createTestImage());

    const res = await fetch(`${getBaseUrl()}/api/workspaces/${slug}/emoji`, {
      method: "POST",
      headers,
      body: formData,
    });
    expect(res.status).toBe(400);
  });

  test("non-image file → 400", async () => {
    const textFile = new File(["hello"], "test.txt", { type: "text/plain" });
    const formData = new FormData();
    formData.append("name", `txt-${testId()}`);
    formData.append("file", textFile);

    const res = await fetch(`${getBaseUrl()}/api/workspaces/${slug}/emoji`, {
      method: "POST",
      headers,
      body: formData,
    });
    expect(res.status).toBe(400);
  });

  test("delete non-existent emoji → 404", async () => {
    const res = await client.api.workspaces[":slug"].emoji[":emojiId"].$delete({
      param: { slug, emojiId: "00000000-0000-0000-0000-000000000000" },
    });
    expect(res.status).toBe(404);
  });
});
